### ISSUE TITLE
Types not included

### ISSUE THREAD

**Issue by ewaldbervoets** [LolipopJ/mdimg#7]
Types aren't included when pulling the project via yarn or npm although they are available in the repository.

**Comment by LolipopJ** [comment]
Oh, that's because type file is not included in release. I'll fix this.

```json
"files": ["bin/", "lib/", "src/", "template/css/", "template/html/"]
```

**Comment by LolipopJ** [comment]
\+ mdimg@0.2.2

Have a try!

I'm planning to reimplement this library in TypeScript, so it will not be a problem.
