### ISSUE TITLE
[Bug Report] File “types.d.ts” is not a module.

### ISSUE THREAD

**Issue by EnchStudio** [LolipopJ/mdimg#8]
the issue appeared in my project when refactoring to typescript i.e. version 1.0.0.

![bb9afad7fc8fef060f5fbf51ee4d6d23](https://github.com/user-attachments/assets/d50b5536-b57b-4ecd-9517-d839a77e7329)

**Comment by LolipopJ** [comment]
Fixed in version [1.1.1](https://www.npmjs.com/package/mdimg/v/1.1.1), thanks for reporting!
