### ISSUE TITLE
[Feature Request] template import with text

### ISSUE THREAD

**Issue by EnchStudio** [LolipopJ/mdimg#9]
same as the title

**Comment by LolipopJ** [comment]
I just release the [1.1.0](https://www.npmjs.com/package/mdimg/v/1.1.0), have a try!

You can follow this [guide](https://github.com/LolipopJ/mdimg?tab=readme-ov-file#intake-template-directly) to import template with text dirctly.

**Comment by LolipopJ** [comment]
If any bugs appear, please let me know.

**Comment by EnchStudio** [comment]
seems work good, thx for your work!
